server.port=8087

spring.r2dbc.url=r2dbc:sqlserver://localhost:1433/BD_CHALLENGE
spring.r2dbc.username=alexischallenge
spring.r2dbc.password=alexispaul

spring.r2dbc.properties.encrypt=true
spring.r2dbc.properties.trustServerCertificate=false

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
